<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            // Platinum member with allergies
            [
                'name' => 'สมชาย ใจดี',
                'nickname' => 'ชาย',
                'phone' => '081-234-5678',
                'email' => 'somchai@email.com',
                'birth_date' => Carbon::now()->subYears(45),
                'gender' => 'male',
                'national_id' => '1100500123456',
                'address' => '123/45 ถ.สุขุมวิท แขวงคลองตัน เขตคลองเตย กรุงเทพฯ 10110',
                'line_id' => 'somchai_jaidee',
                'drug_allergies' => [
                    ['drug_name' => 'Penicillin', 'reaction' => 'ผื่นแดงทั่วตัว หายใจลำบาก'],
                    ['drug_name' => 'Aspirin', 'reaction' => 'บวมตามใบหน้า'],
                ],
                'chronic_diseases' => ['เบาหวาน', 'ความดันโลหิตสูง'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'ทานยาลดความดันทุกวัน ควรหลีกเลี่ยงยาที่มีโซเดียมสูง',
                'points_balance' => 5420,
                'member_tier' => 'platinum',
                'member_since' => Carbon::now()->subYears(3),
                'total_spent' => 68500,
                'visit_count' => 89,
                'last_visit_at' => Carbon::now()->subDays(2),
                'is_active' => true,
            ],
            // Gold member pregnant
            [
                'name' => 'สุดา รักษา',
                'nickname' => 'ดา',
                'phone' => '089-876-5432',
                'email' => 'suda@email.com',
                'birth_date' => Carbon::now()->subYears(32),
                'gender' => 'female',
                'address' => '456 ถ.พหลโยธิน แขวงจตุจักร เขตจตุจักร กรุงเทพฯ 10900',
                'line_id' => 'suda_r',
                'drug_allergies' => [
                    ['drug_name' => 'Sulfonamide', 'reaction' => 'ผื่นคัน'],
                ],
                'chronic_diseases' => [],
                'pregnancy_status' => 'pregnant',
                'medical_notes' => 'ตั้งครรภ์ 6 เดือน ควรระวังยาที่ห้ามใช้ระหว่างตั้งครรภ์',
                'points_balance' => 2850,
                'member_tier' => 'gold',
                'member_since' => Carbon::now()->subYears(2),
                'total_spent' => 28500,
                'visit_count' => 45,
                'last_visit_at' => Carbon::now()->subDays(5),
                'is_active' => true,
            ],
            // Silver member with chronic disease
            [
                'name' => 'มานะ ขยัน',
                'nickname' => 'นะ',
                'phone' => '062-111-2222',
                'birth_date' => Carbon::now()->subYears(55),
                'gender' => 'male',
                'address' => '789 ถ.รัชดาภิเษก แขวงห้วยขวาง',
                'drug_allergies' => [],
                'chronic_diseases' => ['โรคหัวใจ', 'ไขมันในเลือดสูง', 'เบาหวาน'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'ทานยาหัวใจและยาลดไขมันประจำ ต้องระวังปฏิกิริยายา',
                'points_balance' => 1250,
                'member_tier' => 'silver',
                'member_since' => Carbon::now()->subMonths(8),
                'total_spent' => 12500,
                'visit_count' => 22,
                'last_visit_at' => Carbon::now()->subDays(10),
                'is_active' => true,
            ],
            // Regular member breastfeeding
            [
                'name' => 'วิภา มารดา',
                'nickname' => 'อ้อม',
                'phone' => '095-333-4444',
                'email' => 'wipa.m@email.com',
                'birth_date' => Carbon::now()->subYears(28),
                'gender' => 'female',
                'address' => '321 ซ.อารีย์ ถ.พหลโยธิน กรุงเทพฯ',
                'line_id' => 'wipa_mom',
                'drug_allergies' => [],
                'chronic_diseases' => [],
                'pregnancy_status' => 'breastfeeding',
                'medical_notes' => 'ให้นมบุตร ควรหลีกเลี่ยงยาที่ผ่านน้ำนมได้',
                'points_balance' => 450,
                'member_tier' => 'regular',
                'member_since' => Carbon::now()->subMonths(2),
                'total_spent' => 3200,
                'visit_count' => 8,
                'last_visit_at' => Carbon::now()->subDays(3),
                'is_active' => true,
            ],
            // Regular with multiple allergies
            [
                'name' => 'ประภา แพ้ยา',
                'nickname' => 'ภา',
                'phone' => '088-555-6666',
                'birth_date' => Carbon::now()->subYears(38),
                'gender' => 'female',
                'national_id' => '1100700234567',
                'drug_allergies' => [
                    ['drug_name' => 'Ibuprofen', 'reaction' => 'ปวดท้อง อาเจียน'],
                    ['drug_name' => 'Amoxicillin', 'reaction' => 'ผื่นลมพิษ'],
                    ['drug_name' => 'Codeine', 'reaction' => 'คลื่นไส้รุนแรง'],
                ],
                'chronic_diseases' => ['ภูมิแพ้'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'ระบบภูมิคุ้มกันอ่อนแอ แพ้ยาหลายชนิด ควรระวังเป็นพิเศษ',
                'points_balance' => 680,
                'member_tier' => 'regular',
                'member_since' => Carbon::now()->subMonths(4),
                'total_spent' => 4800,
                'visit_count' => 12,
                'last_visit_at' => Carbon::now()->subDays(7),
                'is_active' => true,
            ],
            // Senior citizen
            [
                'name' => 'สมปอง เกษียณ',
                'nickname' => 'ปู่ปอง',
                'phone' => '086-777-8888',
                'birth_date' => Carbon::now()->subYears(72),
                'gender' => 'male',
                'address' => '555 ถ.ลาดพร้าว แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ',
                'drug_allergies' => [
                    ['drug_name' => 'NSAIDs', 'reaction' => 'แผลในกระเพาะ'],
                ],
                'chronic_diseases' => ['ข้อเข่าเสื่อม', 'ต้อกระจก', 'ความดันโลหิตสูง'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'ผู้สูงอายุ ทานยาหลายชนิด ต้องตรวจสอบปฏิกิริยายา',
                'points_balance' => 3200,
                'member_tier' => 'gold',
                'member_since' => Carbon::now()->subYears(1)->subMonths(6),
                'total_spent' => 32000,
                'visit_count' => 48,
                'last_visit_at' => Carbon::now()->subDays(1),
                'is_active' => true,
            ],
            // Young adult no allergies
            [
                'name' => 'กิตติ เฮลตี้',
                'nickname' => 'กิต',
                'phone' => '091-999-0000',
                'email' => 'kitti.h@email.com',
                'birth_date' => Carbon::now()->subYears(25),
                'gender' => 'male',
                'line_id' => 'kitti_healthy',
                'drug_allergies' => [],
                'chronic_diseases' => [],
                'pregnancy_status' => 'none',
                'points_balance' => 180,
                'member_tier' => 'regular',
                'member_since' => Carbon::now()->subWeeks(3),
                'total_spent' => 850,
                'visit_count' => 3,
                'last_visit_at' => Carbon::now()->subDays(14),
                'is_active' => true,
            ],
            // Platinum elderly woman
            [
                'name' => 'สมจิต รักสุขภาพ',
                'nickname' => 'ย่าจิต',
                'phone' => '084-111-3333',
                'birth_date' => Carbon::now()->subYears(68),
                'gender' => 'female',
                'national_id' => '1100300345678',
                'address' => '88 ถ.สาทร แขวงทุ่งมหาเมฆ เขตสาทร กรุงเทพฯ',
                'drug_allergies' => [
                    ['drug_name' => 'Tetracycline', 'reaction' => 'คลื่นไส้'],
                ],
                'chronic_diseases' => ['เบาหวาน', 'กระดูกพรุน'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'รับประทานแคลเซียมและวิตามินดีเสริม',
                'points_balance' => 8500,
                'member_tier' => 'platinum',
                'member_since' => Carbon::now()->subYears(4),
                'total_spent' => 95000,
                'visit_count' => 156,
                'last_visit_at' => Carbon::now()->subHours(6),
                'is_active' => true,
            ],
            // Silver working woman
            [
                'name' => 'นภา ออฟฟิศ',
                'nickname' => 'นา',
                'phone' => '063-222-4444',
                'email' => 'napa.office@company.com',
                'birth_date' => Carbon::now()->subYears(35),
                'gender' => 'female',
                'line_id' => 'napa_work',
                'drug_allergies' => [],
                'chronic_diseases' => ['ไมเกรน'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'มีอาการปวดหัวไมเกรนบ่อย ชอบซื้อยาแก้ปวดไมเกรน',
                'points_balance' => 1850,
                'member_tier' => 'silver',
                'member_since' => Carbon::now()->subMonths(10),
                'total_spent' => 15800,
                'visit_count' => 28,
                'last_visit_at' => Carbon::now()->subDays(4),
                'is_active' => true,
            ],
            // Regular customer
            [
                'name' => 'วิชัย ปกติ',
                'phone' => '097-555-7777',
                'birth_date' => Carbon::now()->subYears(42),
                'gender' => 'male',
                'address' => '777 ถ.รามคำแหง แขวงหัวหมาก เขตบางกะปิ กรุงเทพฯ',
                'drug_allergies' => [],
                'chronic_diseases' => [],
                'pregnancy_status' => 'none',
                'points_balance' => 320,
                'member_tier' => 'regular',
                'member_since' => Carbon::now()->subMonths(1),
                'total_spent' => 2400,
                'visit_count' => 5,
                'last_visit_at' => Carbon::now()->subDays(8),
                'is_active' => true,
            ],
            // Inactive customer
            [
                'name' => 'หายไป นานแล้ว',
                'phone' => '082-888-9999',
                'birth_date' => Carbon::now()->subYears(50),
                'gender' => 'male',
                'drug_allergies' => [],
                'chronic_diseases' => [],
                'pregnancy_status' => 'none',
                'points_balance' => 50,
                'member_tier' => 'regular',
                'member_since' => Carbon::now()->subYears(2),
                'total_spent' => 500,
                'visit_count' => 2,
                'last_visit_at' => Carbon::now()->subMonths(18),
                'is_active' => false,
            ],
            // Gold member with asthma
            [
                'name' => 'ลมหายใจ ดีขึ้น',
                'nickname' => 'ลม',
                'phone' => '064-444-5555',
                'email' => 'lom@breath.com',
                'birth_date' => Carbon::now()->subYears(29),
                'gender' => 'male',
                'line_id' => 'lom_breath',
                'drug_allergies' => [
                    ['drug_name' => 'Beta-blockers', 'reaction' => 'หอบหืดกำเริบ'],
                ],
                'chronic_diseases' => ['หอบหืด'],
                'pregnancy_status' => 'none',
                'medical_notes' => 'ใช้ยาพ่นขยายหลอดลมประจำ ห้ามใช้ยากลุ่ม Beta-blockers',
                'points_balance' => 2100,
                'member_tier' => 'gold',
                'member_since' => Carbon::now()->subMonths(14),
                'total_spent' => 22500,
                'visit_count' => 36,
                'last_visit_at' => Carbon::now()->subDays(6),
                'is_active' => true,
            ],
        ];

        foreach ($customers as $customer) {
            Customer::updateOrCreate(
                ['phone' => $customer['phone']],
                $customer
            );
        }
    }
}
