<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'บริษัท ฟาร์มาซี ซัพพลาย จำกัด',
                'tax_id' => '0105551234567',
                'contact_person' => 'คุณสมชาย',
                'phone' => '02-123-4567',
                'mobile' => '081-234-5678',
                'email' => 'sales@pharmasupply.co.th',
                'line_id' => 'pharmasupply',
                'address' => '123 ถนนสุขุมวิท แขวงคลองตัน เขตคลองเตย กรุงเทพฯ 10110',
                'credit_term' => 30,
                'lead_time' => 3,
                'min_order_qty' => 5000,
                'bank_name' => 'ธนาคารกรุงเทพ',
                'bank_account_no' => '123-4-56789-0',
                'bank_account_name' => 'บริษัท ฟาร์มาซี ซัพพลาย จำกัด',
                'is_active' => true,
            ],
            [
                'name' => 'GPO (องค์การเภสัชกรรม)',
                'tax_id' => '0994000165509',
                'contact_person' => 'ฝ่ายขาย',
                'phone' => '02-203-8000',
                'mobile' => '099-999-9999',
                'email' => 'sales@gpo.or.th',
                'address' => '75/1 ถนนพระรามที่ 6 แขวงทุ่งพญาไท เขตราชเทวี กรุงเทพฯ 10400',
                'credit_term' => 60,
                'lead_time' => 5,
                'min_order_qty' => 10000,
                'bank_name' => 'ธนาคารกรุงไทย',
                'bank_account_no' => '000-1-23456-7',
                'bank_account_name' => 'องค์การเภสัชกรรม',
                'is_active' => true,
            ],
            [
                'name' => 'สยามเฮลท์ แคร์ จำกัด',
                'tax_id' => '0105554567890',
                'contact_person' => 'คุณวิภา',
                'phone' => '02-456-7890',
                'mobile' => '089-876-5432',
                'email' => 'order@siamhealth.co.th',
                'line_id' => 'siamhealth',
                'address' => '456 ถนนพระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10310',
                'credit_term' => 45,
                'lead_time' => 2,
                'min_order_qty' => 3000,
                'bank_name' => 'ธนาคารไทยพาณิชย์',
                'bank_account_no' => '234-5-67890-1',
                'bank_account_name' => 'บริษัท สยามเฮลท์ แคร์ จำกัด',
                'is_active' => true,
            ],
            [
                'name' => 'ไบโอแลบ จำกัด',
                'tax_id' => '0105539876543',
                'contact_person' => 'คุณปิยะ',
                'phone' => '02-789-0123',
                'mobile' => '085-555-1234',
                'email' => 'contact@biolab.co.th',
                'address' => '789 ถนนพหลโยธิน แขวงจตุจักร เขตจตุจักร กรุงเทพฯ 10900',
                'credit_term' => 30,
                'lead_time' => 7,
                'min_order_qty' => 2000,
                'bank_name' => 'ธนาคารกสิกรไทย',
                'bank_account_no' => '345-6-78901-2',
                'bank_account_name' => 'บริษัท ไบโอแลบ จำกัด',
                'is_active' => true,
            ],
            [
                'name' => 'เมดิคอล อินเตอร์ จำกัด',
                'tax_id' => '0105548765432',
                'contact_person' => 'คุณนภา',
                'phone' => '02-321-9876',
                'mobile' => '086-777-8888',
                'email' => 'sales@medicalinter.com',
                'address' => '321 ถนนเพชรบุรี แขวงถนนเพชรบุรี เขตราชเทวี กรุงเทพฯ 10400',
                'credit_term' => 15,
                'lead_time' => 1,
                'min_order_qty' => 1500,
                'bank_name' => 'ธนาคารทหารไทยธนชาต',
                'bank_account_no' => '456-7-89012-3',
                'bank_account_name' => 'บริษัท เมดิคอล อินเตอร์ จำกัด',
                'is_active' => true,
            ],
            [
                'name' => 'เจริญเภสัช จำกัด',
                'tax_id' => '0105520123456',
                'contact_person' => 'คุณอนันต์',
                'phone' => '02-654-3210',
                'mobile' => '082-333-4444',
                'email' => 'info@charoenphesaj.co.th',
                'address' => '654 ถนนราชดำริ แขวงลุมพินี เขตปทุมวัน กรุงเทพฯ 10330',
                'credit_term' => 30,
                'lead_time' => 4,
                'min_order_qty' => 4000,
                'is_active' => true,
            ],
            [
                'name' => 'ไทย เฮลท์แคร์ เน็ตเวิร์ก',
                'tax_id' => '0105560112233',
                'contact_person' => 'คุณพิชัย',
                'phone' => '02-999-0000',
                'mobile' => '084-111-2222',
                'email' => 'contact@thaihealthcare.com',
                'address' => '99/1 ถนนลาดพร้าว เขตบางกะปิ กรุงเทพฯ 10240',
                'credit_term' => 30,
                'lead_time' => 3,
                'min_order_qty' => 2500,
                'is_active' => true,
            ],
            [
                'name' => 'บริษัท โอสถกรุงเทพ จำกัด',
                'tax_id' => '0105530998877',
                'contact_person' => 'คุณธนา',
                'phone' => '02-555-4444',
                'mobile' => '081-999-8888',
                'email' => 'info@osotbangkok.com',
                'address' => '55 ถนนรองเมือง แขวงรองเมือง เขตปทุมวัน กรุงเทพฯ 10330',
                'credit_term' => 45,
                'lead_time' => 4,
                'min_order_qty' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'โรงงานฟาร์มาแลนด์ จำกัด',
                'tax_id' => '0105540776655',
                'contact_person' => 'คุณสุวรรณ',
                'phone' => '02-888-7777',
                'mobile' => '087-666-5555',
                'email' => 'factory@pharmaland.co.th',
                'address' => '88 หมู่ 5 นิคมอุตสาหกรรมบางปู จ.สมุทรปราการ 10280',
                'credit_term' => 60,
                'lead_time' => 10,
                'min_order_qty' => 10000,
                'is_active' => true,
            ],
            [
                'name' => 'ยูเนี่ยน เมดิคอล เซ็นเตอร์',
                'tax_id' => '0105555443322',
                'contact_person' => 'คุณมานะ',
                'phone' => '02-777-6666',
                'mobile' => '083-444-5555',
                'email' => 'sales@unionmedical.com',
                'address' => '44 ถนนสาทร เขตสาทร กรุงเทพฯ 10120',
                'credit_term' => 30,
                'lead_time' => 2,
                'min_order_qty' => 2000,
                'is_active' => true,
            ],
            [
                'name' => 'บริษัท ยาไทยอินเตอร์เนชั่นแนล จำกัด',
                'tax_id' => '0105522114455',
                'contact_person' => 'คุณจารุวรรณ',
                'phone' => '02-222-1111',
                'mobile' => '080-111-9999',
                'email' => 'export@thaipharma.com',
                'address' => '11 ถนนเจริญกรุง เขตบางรัก กรุงเทพฯ 10500',
                'credit_term' => 30,
                'lead_time' => 5,
                'min_order_qty' => 3500,
                'is_active' => true,
            ],
            [
                'name' => 'เมดไลน์ แฟคตอรี่',
                'tax_id' => '0105544338877',
                'contact_person' => 'คุณเกรียงไกร',
                'phone' => '02-333-5555',
                'mobile' => '089-222-3333',
                'email' => 'production@medlinefactory.co.th',
                'address' => '33/5 ถนนเพชรเกษม เขตหนองแขม กรุงเทพฯ 10160',
                'credit_term' => 15,
                'lead_time' => 3,
                'min_order_qty' => 1000,
                'is_active' => true,
            ],
            [
                'name' => 'เบอร์ลินฟาร์มาซูติคอล จำกัด',
                'tax_id' => '0105511002233',
                'contact_person' => 'คุณรุจิรา',
                'phone' => '02-111-2222',
                'mobile' => '088-333-7777',
                'email' => 'info@berlinpharma.com',
                'address' => '100 ถนนวิทยุ เขตปทุมวัน กรุงเทพฯ 10330',
                'credit_term' => 45,
                'lead_time' => 6,
                'min_order_qty' => 5000,
                'is_active' => true,
            ],
            [
                'name' => 'บริษัท พรีมีดิก้า จำกัด',
                'tax_id' => '0105549001122',
                'contact_person' => 'คุณอธิป',
                'phone' => '02-444-9999',
                'mobile' => '086-111-0000',
                'email' => 'care@premedica.co.th',
                'address' => '11/9 ถนนเยาวราช เขตสัมพันธวงศ์ กรุงเทพฯ 10100',
                'credit_term' => 30,
                'lead_time' => 3,
                'min_order_qty' => 3000,
                'is_active' => true,
            ],
            [
                'name' => 'สหยา จำกัด',
                'tax_id' => '0105559008877',
                'contact_person' => 'คุณเกรียงศักดิ์',
                'phone' => '02-555-6666',
                'mobile' => '082-222-1111',
                'email' => 'contact@sahaya.co.th',
                'address' => '555 ถนนสุขุมวิท เขตวัฒนา กรุงเทพฯ 10110',
                'credit_term' => 30,
                'lead_time' => 4,
                'min_order_qty' => 2000,
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }

        $this->command->info('Created ' . count($suppliers) . ' suppliers!');
    }
}
