<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Admin User',
                'username' => 'admin',
                'email' => 'admin@oboun.local',
                'phone' => '080-000-0000',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'position' => 'System Administrator',
                'status' => 'active',
                'hired_date' => now(),
            ],
            [
                'name' => 'Staff User',
                'username' => 'staff',
                'email' => 'staff@oboun.local',
                'phone' => '080-000-0001',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'Store Staff',
                'status' => 'active',
                'hired_date' => now(),
            ],
            [
                'name' => 'ดร.สมชาย ใจดี',
                'username' => 'somchai.admin',
                'email' => 'somchai@obounerp.com',
                'phone' => '081-234-5678',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'position' => 'เภสัชกรผู้จัดการ',
                'pharmacist_license_no' => 'ภ.12345',
                'license_expiry' => now()->addYears(2),
                'status' => 'active',
                'hired_date' => now()->subYears(5),
                'notes' => 'ผู้ดูแลระบบหลัก มีประสบการณ์ 15 ปี',
            ],
            [
                'name' => 'ภญ.สุดา รักษ์ดี',
                'username' => 'suda.pharm',
                'email' => 'suda@obounerp.com',
                'phone' => '082-345-6789',
                'password' => Hash::make('password'),
                'role' => 'pharmacist',
                'position' => 'เภสัชกรอาวุโส',
                'pharmacist_license_no' => 'ภ.23456',
                'license_expiry' => now()->addMonths(6), // Expiring soon
                'status' => 'active',
                'hired_date' => now()->subYears(3),
                'notes' => 'เชี่ยวชาญด้านยาเฉพาะทาง',
            ],
            [
                'name' => 'ภญ.วิภา สุขสม',
                'username' => 'wipa.pharm',
                'email' => 'wipa@obounerp.com',
                'phone' => '083-456-7890',
                'password' => Hash::make('password'),
                'role' => 'pharmacist',
                'position' => 'เภสัชกร',
                'pharmacist_license_no' => 'ภ.34567',
                'license_expiry' => now()->addYears(3),
                'status' => 'active',
                'hired_date' => now()->subYears(2),
                'notes' => 'รับผิดชอบแผนกยาปฏิชีวนะ',
            ],
            [
                'name' => 'นายประยุทธ์ ขยัน',
                'username' => 'prayut.staff',
                'email' => 'prayut@obounerp.com',
                'phone' => '084-567-8901',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'พนักงานขาย',
                'status' => 'active',
                'hired_date' => now()->subYear(),
                'notes' => 'พนักงานขายประจำเคาน์เตอร์',
            ],
            [
                'name' => 'นางสาวมาลี สวยงาม',
                'username' => 'malee.staff',
                'email' => 'malee@obounerp.com',
                'phone' => '085-678-9012',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'พนักงานขาย',
                'status' => 'active',
                'hired_date' => now()->subMonths(8),
                'notes' => 'พนักงานขายกะเช้า',
            ],
            [
                'name' => 'นายสมศักดิ์ เก่งกาจ',
                'username' => 'somsak.staff',
                'email' => 'somsak@obounerp.com',
                'phone' => '086-789-0123',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'พนักงานขาย',
                'status' => 'suspended',
                'hired_date' => now()->subMonths(6),
                'notes' => 'พักงานชั่วคราว - เหตุส่วนตัว',
            ],
            [
                'name' => 'นางสาวจิรา ดีมาก',
                'username' => 'jira.resigned',
                'email' => 'jira@obounerp.com',
                'phone' => '087-890-1234',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'พนักงานขาย (เดิม)',
                'status' => 'resigned',
                'hired_date' => now()->subYears(2),
                'notes' => 'ลาออกเมื่อ 3 เดือนที่แล้ว - ย้ายไปต่างจังหวัด',
            ],
            [
                'name' => 'นายวิชัย มานะ',
                'username' => 'wichai.admin',
                'email' => 'wichai@obounerp.com',
                'phone' => '088-901-2345',
                'password' => Hash::make('password'),
                'role' => 'admin',
                'position' => 'ผู้ช่วยผู้จัดการ',
                'status' => 'active',
                'hired_date' => now()->subYears(4),
                'notes' => 'ดูแลระบบไอทีและสินค้าคงคลัง',
            ],
            [
                'name' => 'ภญ.นารี รัตนา',
                'username' => 'naree.pharm',
                'email' => 'naree@obounerp.com',
                'phone' => '089-012-3456',
                'password' => Hash::make('password'),
                'role' => 'pharmacist',
                'position' => 'เภสัชกรพาร์ทไทม์',
                'pharmacist_license_no' => 'ภ.45678',
                'license_expiry' => now()->addDays(15), // Expiring very soon
                'status' => 'active',
                'hired_date' => now()->subYear(),
            ],
            [
                'name' => 'นายกานต์ สุขใจ',
                'username' => 'karn.staff',
                'email' => 'karn@obounerp.com',
                'phone' => '090-123-4567',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'แคชเชียร์',
                'status' => 'active',
                'hired_date' => now()->subMonths(3),
            ],
            [
                'name' => 'นางสาวเบญจา ใจเย็น',
                'username' => 'benja.staff',
                'email' => 'benja@obounerp.com',
                'phone' => '091-234-5678',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'แคชเชียร์',
                'status' => 'active',
                'hired_date' => now()->subMonths(2),
            ],
            [
                'name' => 'นายฉัตรชัย รักยา',
                'username' => 'chatchai.pharm',
                'email' => 'chatchai@obounerp.com',
                'phone' => '092-345-6789',
                'password' => Hash::make('password'),
                'role' => 'pharmacist',
                'position' => 'เภสัชกรกะกลางคืน',
                'pharmacist_license_no' => 'ภ.56789',
                'license_expiry' => now()->subDays(5), // Already expired
                'status' => 'active',
                'hired_date' => now()->subMonths(10),
            ],
            [
                'name' => 'นางสาวดวงใจ มีสุข',
                'username' => 'duangjai.staff',
                'email' => 'duangjai@obounerp.com',
                'phone' => '093-456-7890',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'ฝ่ายคลังสินค้า',
                'status' => 'active',
                'hired_date' => now()->subMonths(5),
            ],
            [
                'name' => 'นายเอกพล พากเพียร',
                'username' => 'ekapol.staff',
                'email' => 'ekapol@obounerp.com',
                'phone' => '094-567-8901',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'ฝ่ายส่งมอบยา',
                'status' => 'active',
                'hired_date' => now()->subMonths(4),
            ],
            [
                'name' => 'นางสาวฟ้า ใสใส',
                'username' => 'fah.staff',
                'email' => 'fah@obounerp.com',
                'phone' => '095-678-9012',
                'password' => Hash::make('password'),
                'role' => 'staff',
                'position' => 'ประชาสัมพันธ์',
                'status' => 'active',
                'hired_date' => now()->subMonths(1),
            ],
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }
    }
}
