services:
  - type: web
    name: oboun-erp
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_KEY
        value: "base64:A2hYSza9e0sUZcBE+yYToEeSu9+tADKKZO2wa0RVv4Q="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: oboun-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: oboun-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: oboun-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: oboun-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: oboun-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_NAME
        value: ObounERP

databases:
  - name: oboun-db
    plan: free
    region: singapore
